---
- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - git
    - git-extras
    - wget
    - speedtest_cli

- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - slack
    - google-chrome
    - firefox
    - evernote
    - xmind
    - the-unarchiver
    - box-sync
    - lastpass
    - appcleaner
    - prezi
    - caffeine
    - displaylink
    - dropbox
    - microsoft-office

- name: install cask fonts for all users
  homebrew_cask_fonts: name={{item}} state=present
    - ubuntu-mono-powerline
    - ubuntu
    - lato
    - source-sans-pro
