---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - git
    - git-extras
    - pyenv-virtualenv
    - pyenv-virtualenvwrapper
    - pyenv-pip-migrate
    - wget
    - awscli

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - python3
    - vagrant
    - virtualbox
    - python
    - packer
